Refactor in webhook process
mobbexco/magento pull request #26
Opened 2022-02-03 14:56 UTC by Emitsu55

2022-03-04 19:46 UTC, jlmobbex requested changes

2022-03-04 19:46 UTC, jlmobbex commented on app/design/adminhtml/base/default/template/mobbex/financingamountadmin.phtml
> +    if($data['data']){
Acá ocurre el mismo problema sobre el cambio el el método `getMobbexTransaction`. También se está haciendo un json_decode de la colección que arroja error

2022-03-04 19:46 UTC, jlmobbex commented on app/design/frontend/base/default/template/mobbex/financingamount.phtml
> +    if($data['data']){
Y acá también está ocurriendo el mismo problema con el método `getMobbexTransaction`

2022-03-04 19:46 UTC, jlmobbex commented on app/code/local/Mobbex/Mobbex/sql/mobbex_mobbex_setup/upgrade-1.4.2-1.5.0.php
> +        ->addColumn('Source_url', Varien_Db_Ddl_Table::TYPE_TEXT, null, array(
Hay un pequeño error de tipeo por acá, la columna `source_url` se está añadiendo con una mayúscula al principio (esto puede llevar a errores dependiendo el motor de la db). Y menciono el mismo detalle menor que agregué más arriba! Estaría genial si pueden estar juntas las columnas del source

2022-03-04 19:46 UTC, jlmobbex commented on app/code/local/Mobbex/Mobbex/sql/mobbex_mobbex_setup/upgrade-1.4.2-1.5.0.php
> +        ), 'Risk analysis')
Esta columna (`risk_analysis`) se está insertando de forma duplicada

2022-03-04 19:46 UTC, jlmobbex commented on app/code/local/Mobbex/Mobbex/sql/mobbex_mobbex_setup/upgrade-1.4.2-1.5.0.php
> +    ADD COLUMN `source_url` TEXT NOT NULL,
Otro detalle muy menor, es que esta columna quedó separada del resto de columnas relacionadas al source, estaría genial si pueden quedar juntas para que quede más fácil de leer en la db

2022-03-04 20:06 UTC, Emitsu55 commented on app/code/local/Mobbex/Mobbex/Model/Observer.php
> +			if($data['data']){
getMobbexTransaction() solo devuelve la data de webhook padre salvo que el param $parent (que por defecto es true) este seteado como "false"

2022-03-04 20:06 UTC, Emitsu55 commented on app/design/frontend/base/default/template/mobbex/financingamount.phtml
> +    if($data['data']){
getMobbexTransaction() solo devuelve la data de webhook padre salvo que el param $parent (que por defecto es true) este seteado como "false"

2022-03-07 17:40 UTC, jlmobbex requested changes

2022-03-07 17:40 UTC, jlmobbex commented on app/design/adminhtml/base/default/template/mobbex/financingamountadmin.phtml
> +    if($data['data']){
Acá habría que agregar una verificación antes de acceder a la posición data (en caso de que se use otro método de pago $data vendría como false)

2022-03-07 17:40 UTC, jlmobbex commented on app/design/frontend/base/default/template/mobbex/financingamount.phtml
> +    if($data['data']){
Mismo detalle por acá, queda agregar la verificación de que está seteada la posicón data

2022-03-07 17:40 UTC, jlmobbex commented on app/code/local/Mobbex/Mobbex/Model/Observer.php
> +			if($data['data']){
Por acá también hay que agregar la verificación de que esté seteada la posición data

2022-03-07 17:40 UTC, jlmobbex commented on app/code/local/Mobbex/Mobbex/Model/Transaction.php
> +        $transaction->setData('source_url', $data['source_url']);
Un detalle que se pasó de la última revisión, para los que actualizan queda separada la columna `source_url` del resto de los datos del source

2022-03-14 02:54 UTC, merged