Added improved customization options
mobbexco/magento pull request #28
Opened 2022-02-23 16:55 UTC by Emitsu55

2022-03-14 04:13 UTC, jlmobbex requested changes

2022-03-14 04:13 UTC, jlmobbex commented on app/code/local/Mobbex/Mobbex/etc/config.xml
> +/* Para que los estilos funcionen deben respetar la sintaxys de CSS.*/
Acá hay un pequeño error tipográfico en la palabra sintaxis, y ya que estoy aprovecho para comentar que estaría genial pasar a español el comentario "Hover options", así queda más claro que función tiene el selector

2022-03-14 04:13 UTC, jlmobbex commented on app/code/local/Mobbex/Mobbex/etc/system.xml
> +						<comment>Set the styles of the finance widget respecting the CSS sintaxys.</comment>
Mismo error tipográfico en la palabra sintaxis (acá iría syntaxis ya que está en inglés)

2022-03-17 20:57 UTC, Emitsu55 commented
Duplicate of #32

2022-03-17 20:57 UTC, closed without merging